---

- name:             Setup wp-cli
  get_url:
    url:            https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest:           /usr/local/bin/wp
    mode:           0755
    owner:          root
    group:          root

- include_tasks:    process-user.yml
  vars:
    user:          "{{ user }}"
  loop_control:
    loop_var:      user
  with_dict:       "{{ froxlor_users }}"

