---

- include_vars:     "{{ ansible_distribution }}.yml"

- name:             install fail2ban
  package:          name={{ item }} state=present
  with_items:
    - "{{ pkgs_fail2ban }}"

- name:             fetch server IP
  shell:            ifconfig | egrep -o '([0-9]{1,3}\.){3}[0-9]{1,3}' | egrep -v '255|10|(127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})' | head -n1
  register:         f2b_ip
  failed_when:      false
  changed_when:     false

- name:             download wordpress related filters (optional)
  get_url:          url={{ item }} dest=/etc/fail2ban/filter.d/ owner=root group=root mode=0640
  notify:           restart fail2ban
  when:             wordpress_fail2ban_secure == true
  with_items:
    - "{{ wordpress_fail2ban_filters }}"

- name:             copy fail2ban.conf
  copy:             src=fail2ban.conf dest=/etc/fail2ban/fail2ban.conf force=yes owner=root group=root mode=0644
  notify:           restart fail2ban

- name:             copy jail.conf
  template:         src=jail.redhat.conf.j2 dest=/etc/fail2ban/jail.conf force=yes owner=root group=root mode=0644
  notify:           restart fail2ban
  when:             ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name:             copy jail.conf
  template:         src=jail.debian.conf.j2 dest=/etc/fail2ban/jail.conf force=yes owner=root group=root mode=0644
  notify:           restart fail2ban
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name:             copy action.d/ufw-ssh.conf
  copy:             src=ufw-ssh.conf dest=/etc/fail2ban/action.d/ufw-ssh.conf force=yes owner=root group=root mode=0644
  notify:           restart fail2ban
  when:             ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name:             copy logrotate.d/fail2ban
  template:         src=fail2ban.logrotate.j2 dest=/etc/logrotate.d/fail2ban owner=root group=root mode=0644

- name:             remove /etc/fail2ban/jail.d/defaults-debian.conf if present
  file:             path=/etc/fail2ban/jail.d/defaults-debian.conf state=absent
